import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "./Provider";
import { Bai_Jamjuree } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const bai_Jamjuree = Bai_Jamjuree({
  weight: '500',
  subsets:['latin','thai']
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistMono.variable} ${geistMono.variable} antialiased`}
        >
          <Provider>
            <Navbar />

            <main className="container ">{children}</main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
